mariadb:
  image:
    repository: bitnamilegacy/mariadb
    tag: latest

  architecture: standalone

  auth:
    database: demo
    username: demo
    password: demo
    rootPassword: root

  primary:
    livenessProbe:
      enabled: false
    readinessProbe:
      enabled: false