apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: demo-dev
  namespace: argocd
  annotations:
    argocd.argoproj.io/sync-options: RespectSyncWave=true
spec:
  project: default
  source:
    repoURL: https://github.com/FaresMirza/wavetest.git
    targetRevision: HEAD
    path: clusters/inpro-dev/demo/apps
  destination:
    name: in-cluster
    namespace: argocd
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
      - RespectSyncWave=true