apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: my-frontend
  namespace: argocd
  annotations:
    argocd.argoproj.io/sync-wave: "3"
    argocd.argoproj.io/depends-on: '[{"name":"my-api"}]'  
  finalizers:
    - resources-finalizer.argocd.argoproj.io
spec:
  project: default

  source:
    repoURL: https://github.com/FaresMirza/wavetest.git
    targetRevision: HEAD
    path: ./manifests/frontend
   
  destination:
    server: https://kubernetes.default.svc
    namespace: my-frontend

  # Sync policy
  syncPolicy:
    syncOptions:
      - CreateNamespace=true  
    automated: 
      prune: true
      selfHeal: true 
  
